--- #YAML:1.0
name:               WAP-SAXDriver-wbxml
version:            2.07
abstract:           SAX2 parser for WBXML file used by Wireless Application Protocol
author:
    - Francois PERRAD (francois.perrad@gadz.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    I18N::Charset:     1.15
    IO::String:        0
    WAP::wbxml:        1.13
    XML::SAX:          0.12
    XML::SAX::Writer:  0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
