#!/usr/bin/perl -w

use strict;

use XML::Handler::BuildDOM;
use WAP::SAXDriver::wbxml;

my $handler = new XML::Handler::BuildDOM();
my $parser = new WAP::SAXDriver::wbxml(Handler => $handler);

my $file = $ARGV[0];
my $io = new IO::File($file,"r");
die "Can't open $file ($!)\n"
		unless (defined $io);

my $doc = $parser->parse(
		Source		=> {ByteStream => $io}
);

$doc->printToFileHandle (\*STDOUT);

__END__

=head1 NAME

xmld - XML Disassembler

=head1 SYNOPSYS

 xmld I<file>

=head1 DESCRIPTION

B<xmld> disassembles binarized XML into XML.

B<xmld> needs XML::DOM and XML::Handler::BuildDOM modules.

WAP Specifications, including Binary XML Content Format (WBXML)
 are available on E<lt>http://www.wapforum.org/E<gt>.

=head1 SEE ALSO

 WAP::SAXDriver::wbxml, WAP::wbxml, xmlc

=head1 AUTHOR

Francois PERRAD E<lt>perrad@besancon.sema.slb.comE<gt>

=cut
